DROP TABLE IF EXISTS ODONTOLOGOS;
CREATE TABLE ODONTOLOGOS (ID INT AUTO_INCREMENT PRIMARY KEY, NUMERO_DE_MATRICULA INT NOT NULL, NOMBRE VARCHAR(100) NOT NULL, APELLIDO VARCHAR(100) NOT NULL);

-- INSERTAMOS ODONTOLOGOS PREVIO AL TEST --
INSERT INTO ODONTOLOGOS(NUMERO_DE_MATRICULA, NOMBRE, APELLIDO) VALUES (4562, 'Agustina', 'Barca'), (7535, 'Nicolas', 'Cardozo');
